### ISSUE TITLE
rebuilt tags fails on Mac OS X Lion

### ISSUE THREAD

**Issue by dcoder2012** [SublimeText/CTags#46]
The ctagsplugin does not work correctly on my iMac with Mac OS X Lion 10.7.4. Every time, when I rebuild the tags, ctagsplugin either runs forever (not stopping), or prints error information on Python console terminal as below:

Traceback (most recent call last):
File "./sublime_plugin.py", line 362, in run_
File "./ctagsplugin.py", line 597, in run
File "./ctagsplugin.py", line 196, in find_top_folder
File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/posixpath.py", line 119, in dirname
i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'

This problem is not sovled even after I change the Python version from 2.7 (default Python version for Mac OS X 10.7 Lion) to 2.6 by using cmd below:
"defaults write com.apple.versioner.python Version 2.6"

But I can still use the "Navigate to Definition" and "Jump back" functions even error information above is printed for "rebuilt tags" step. But these two functions work in a weird way. For example, if I use N times of "Navigate to Definition", then I need to use exact N times of "Jump back" to actually jump back (no matter if some of "Navigate to Definition" actions do not effect when cursor is already on the definition place).

I also posted this issue at another place:
https://www.sublimetext.com/forum/viewtopic.php?f=3&t=3893
